import * as React from "react"

const MOBILE_BREAKPOINT = 768

/**
 * Generated by `shadcn add sidebar`, rewritten on useSyncExternalStore because
 * the original set state inside an effect, which this project's lint rejects.
 * Keep the registry filename so a future `shadcn add` updates this file.
 */
function subscribe(onStoreChange: () => void) {
  const query = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT - 1}px)`)
  query.addEventListener("change", onStoreChange)
  return () => query.removeEventListener("change", onStoreChange)
}

export function useIsMobile() {
  return React.useSyncExternalStore(
    subscribe,
    () => window.innerWidth < MOBILE_BREAKPOINT,
    () => false
  )
}
